model: 
  in_dim: 156 # 52 or 156
  hidden_dims: [128, 128, 64, 64, 32, 32, 16, 16]
  beta: 3
  lr: 1e-3


data: 
  dir: 'src/data/processed/landmark_cleanhip_centered/joint_scaled.pt'
  train_batch_size: 64
  val_batch_size: 64
  num_workers: 8


trainer_params: 
  gpus : [0]
  max_epochs: 100

tensorboard: 
  logdir: "src/VAE/logdir"
  name: 'landmarks' # landmarks or no_landmarks


plots: 
  label_path : 'src/data/processed/labels.pkl'
  min_cluster_size: 10
  umap_interval : 5
  umap_input: 10000


