model: 
  in_dim: 156 # 52 or 156
  hidden_dims: []
  beta: 1
  lr: 1e-3
  latent_dim: 24


data: 
  dir: 'src/data/processed/data/concatenated_tensor.pt'
  train_batch_size: 64
  val_batch_size: 64
  num_workers: 8


trainer_params: 
  gpus : [0]
  max_epochs: 200

tensorboard: 
  logdir: "src/VAE/logdir"
  name: 'landmarks' # landmarks or no_landmarks


plots: 
  label_path : 'src/data/processed/labels.pkl'
  min_cluster_size: 10
  umap_interval : 2
  umap_input: 10000


train: 
  retrive : False
  retrive_path : ''